// Generated by Supabase CLI - DO NOT EDIT DIRECTLY
// This file is auto-generated from your database schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      news_orgs: {
        Row: {
          id: string
          name: string
          slug: string
          owner_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          owner_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          owner_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      news_org_members: {
        Row: {
          id: string
          org_id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id: string
          role: string
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
      }
      news_plans: {
        Row: {
          id: string
          name: string
          description: string | null
          price_monthly: number
          stripe_price_id: string | null
          monthly_quota: Json
          features: Json
          created_at: string
        }
        Insert: {
          id: string
          name: string
          description?: string | null
          price_monthly?: number
          stripe_price_id?: string | null
          monthly_quota?: Json
          features?: Json
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          price_monthly?: number
          stripe_price_id?: string | null
          monthly_quota?: Json
          features?: Json
          created_at?: string
        }
      }
      news_subscriptions: {
        Row: {
          id: string
          org_id: string
          plan_id: string
          status: string
          stripe_subscription_id: string | null
          stripe_customer_id: string | null
          current_period_start: string | null
          current_period_end: string | null
          cancel_at_period_end: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          plan_id: string
          status: string
          stripe_subscription_id?: string | null
          stripe_customer_id?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          plan_id?: string
          status?: string
          stripe_subscription_id?: string | null
          stripe_customer_id?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      news_usage_counters: {
        Row: {
          id: string
          org_id: string
          metric: string
          count: number
          period_start: string
          period_end: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          metric: string
          count?: number
          period_start: string
          period_end: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          metric?: string
          count?: number
          period_start?: string
          period_end?: string
          created_at?: string
          updated_at?: string
        }
      }
      news_sources: {
        Row: {
          id: string
          name: string
          url: string
          ideology: string | null
          country_code: string
          reliability_score: number | null
          active: boolean
          metadata: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          url: string
          ideology?: string | null
          country_code?: string
          reliability_score?: number | null
          active?: boolean
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          url?: string
          ideology?: string | null
          country_code?: string
          reliability_score?: number | null
          active?: boolean
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      news_groups: {
        Row: {
          id: string
          title: string
          summary: string | null
          keywords: string[] | null
          date: string
          country_code: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          summary?: string | null
          keywords?: string[] | null
          date: string
          country_code?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          summary?: string | null
          keywords?: string[] | null
          date?: string
          country_code?: string
          created_at?: string
          updated_at?: string
        }
      }
      news_articles: {
        Row: {
          id: string
          group_id: string
          source_id: string
          title: string
          url: string
          content: string | null
          excerpt: string | null
          published_at: string | null
          ideology: string | null
          sentiment_score: number | null
          created_at: string
        }
        Insert: {
          id?: string
          group_id: string
          source_id: string
          title: string
          url: string
          content?: string | null
          excerpt?: string | null
          published_at?: string | null
          ideology?: string | null
          sentiment_score?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          group_id?: string
          source_id?: string
          title?: string
          url?: string
          content?: string | null
          excerpt?: string | null
          published_at?: string | null
          ideology?: string | null
          sentiment_score?: number | null
          created_at?: string
        }
      }
      news_group_status: {
        Row: {
          id: string
          user_id: string
          group_id: string
          saved: boolean
          archived: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          group_id: string
          saved?: boolean
          archived?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          group_id?: string
          saved?: boolean
          archived?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      news_composer_drafts: {
        Row: {
          id: string
          org_id: string
          user_id: string
          type: string
          template_id: string | null
          subject: string | null
          content: string
          metadata: Json | null
          published: boolean
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id: string
          type: string
          template_id?: string | null
          subject?: string | null
          content: string
          metadata?: Json | null
          published?: boolean
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          user_id?: string
          type?: string
          template_id?: string | null
          subject?: string | null
          content?: string
          metadata?: Json | null
          published?: boolean
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      news_composer_templates: {
        Row: {
          id: string
          name: string
          type: string
          content: string
          variables: string[] | null
          active: boolean
          created_at: string
        }
        Insert: {
          id: string
          name: string
          type: string
          content: string
          variables?: string[] | null
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          type?: string
          content?: string
          variables?: string[] | null
          active?: boolean
          created_at?: string
        }
      }
      news_shortlinks: {
        Row: {
          id: string
          org_id: string
          code: string
          target_url: string
          title: string | null
          clicks: number
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          code: string
          target_url: string
          title?: string | null
          clicks?: number
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          code?: string
          target_url?: string
          title?: string | null
          clicks?: number
          created_at?: string
        }
      }
      news_events: {
        Row: {
          id: string
          org_id: string | null
          user_id: string | null
          session_id: string
          event_name: string
          properties: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          org_id?: string | null
          user_id?: string | null
          session_id: string
          event_name: string
          properties?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string | null
          user_id?: string | null
          session_id?: string
          event_name?: string
          properties?: Json | null
          created_at?: string
        }
      }
      news_source_metrics_daily: {
        Row: {
          id: string
          source_id: string
          date: string
          impressions: number
          clicks: number
          avg_dwell_seconds: number | null
          created_at: string
        }
        Insert: {
          id?: string
          source_id: string
          date: string
          impressions?: number
          clicks?: number
          avg_dwell_seconds?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          source_id?: string
          date?: string
          impressions?: number
          clicks?: number
          avg_dwell_seconds?: number | null
          created_at?: string
        }
      }
      news_rate_limits: {
        Row: {
          id: string
          key: string
          bucket: string
          count: number
          window_start: string
          created_at: string
        }
        Insert: {
          id?: string
          key: string
          bucket: string
          count?: number
          window_start: string
          created_at?: string
        }
        Update: {
          id?: string
          key?: string
          bucket?: string
          count?: number
          window_start?: string
          created_at?: string
        }
      }
      news_api_keys: {
        Row: {
          id: string
          org_id: string
          name: string
          key_hash: string
          prefix: string
          last_used_at: string | null
          created_at: string
          revoked_at: string | null
        }
        Insert: {
          id?: string
          org_id: string
          name: string
          key_hash: string
          prefix: string
          last_used_at?: string | null
          created_at?: string
          revoked_at?: string | null
        }
        Update: {
          id?: string
          org_id?: string
          name?: string
          key_hash?: string
          prefix?: string
          last_used_at?: string | null
          created_at?: string
          revoked_at?: string | null
        }
      }
      news_coupons: {
        Row: {
          id: string
          code: string
          discount_percent: number | null
          discount_amount: number | null
          max_uses: number | null
          uses_count: number
          expires_at: string | null
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          code: string
          discount_percent?: number | null
          discount_amount?: number | null
          max_uses?: number | null
          uses_count?: number
          expires_at?: string | null
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          code?: string
          discount_percent?: number | null
          discount_amount?: number | null
          max_uses?: number | null
          uses_count?: number
          expires_at?: string | null
          active?: boolean
          created_at?: string
        }
      }
      news_referrals: {
        Row: {
          id: string
          referrer_org_id: string
          referred_org_id: string
          code: string
          reward_amount: number | null
          rewarded: boolean
          created_at: string
        }
        Insert: {
          id?: string
          referrer_org_id: string
          referred_org_id: string
          code: string
          reward_amount?: number | null
          rewarded?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          referrer_org_id?: string
          referred_org_id?: string
          code?: string
          reward_amount?: number | null
          rewarded?: boolean
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      bump_news_usage: {
        Args: {
          p_org: string
          p_metric: string
          p_inc?: number
        }
        Returns: number
      }
      bump_news_rate: {
        Args: {
          p_key: string
          p_bucket: string
          p_inc?: number
          p_window_secs?: number
        }
        Returns: number
      }
      rollup_news_source_metrics: {
        Args: {
          p_date: string
        }
        Returns: void
      }
      get_news_patterns: {
        Args: {
          p_start_date: string
          p_end_date: string
        }
        Returns: {
          date: string
          total_groups: number
          conservative_articles: number
          liberal_articles: number
          neutral_articles: number
          avg_conservative_sentiment: number
          avg_liberal_sentiment: number
          top_keywords: string[]
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
